In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataset.csv')
df.head()

,State,Year,Nitrogen (%),Nitrogen (Pounds/Acre),Phosphorous (%),Phosphorous (Pounds/Acre),Potash (%),Potash (Pounds/Acre),Area Planted (acres),Harvested Area (acres),Lint Yield (Pounds/Harvested Acre)
0,Alabama,1964,99.0,72.0,100.0,62.0,99.0,63.0,NaN,NaN,NaN
1,Alabama,1965,100.0,81.0,100.0,63.0,100.0,66.0,NaN,NaN,NaN
2,Alabama,1966,100.0,83.0,100.0,69.0,100.0,70.0,NaN,NaN,NaN
3,Alabama,1967,100.0,78.0,100.0,71.0,100.0,73.0,NaN,NaN,NaN
4,Alabama,1968,100.0,71.0,99.0,71.0,99.0,73.0,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 11 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   State                               756 non-null    object
 1   Year                                756 non-null    int64
 2   Nitrogen (%)                        468 non-null    float64
 3   Nitrogen (Pounds/Acre)              468 non-null    float64
 4   Phosphorous (%)                     468 non-null    float64
 5   Phosphorous (Pounds/Acre)           468 non-null    float64
 6   Potash (%)                          462 non-null    float64
 7   Potash (Pounds/Acre)                458 non-null    float64
 8   Area Planted (acres)                630 non-null    float64
 9   Harvested Area (acres)              630 non-null    float64
 10  Lint Yield (Pounds/Harvested Acre)  630 non-null    float64
dtypes: float64(9), int64(1), object(1)
memory usage: 65.1+ KB

In [6]:
df.describe()

,Year,Nitrogen (%),Nitrogen (Pounds/Acre),Phosphorous (%),Phosphorous (Pounds/Acre),Potash (%),Potash (Pounds/Acre),Area Planted (acres),Harvested Area (acres),Lint Yield (Pounds/Harvested Acre)
count,756.000000,468.000000,468.000000,468.000000,468.000000,462.000000,458.000000,630.000000,630.000000,630.000000
mean,1990.500000,89.521368,87.205128,65.450855,53.367521,58.660173,58.192140,874.279365,778.571429,772.487302
std,15.596102,16.834424,31.770601,24.264596,13.212056,36.089057,29.064521,1454.752247,1186.351037,312.577798
min,1964.000000,29.000000,19.000000,16.000000,23.000000,1.000000,1.000000,31.000000,30.000000,174.000000
25%,1977.000000,91.000000,66.750000,44.000000,44.000000,20.000000,35.250000,230.000000,210.000000,545.500000
50%,1990.500000,97.000000,84.000000,63.000000,53.000000,68.000000,61.500000,397.500000,379.500000,723.500000
75%,2004.000000,100.000000,104.000000,91.000000,62.000000,94.000000,80.000000,810.000000,800.000000,953.000000
max,2017.000000,100.000000,223.000000,100.000000,116.000000,100.000000,118.000000,7850.000000,7200.000000,1910.000000

In [7]:
df['State'].value_counts()

Alabama           54
Arizona           54
Arkansas          54
California        54
Georgia           54
Louisiana         54
Mississippi       54
Missouri          54
New Mexico        54
North Carolina    54
Oklahoma          54
South Carolina    54
Tennessee         54
Texas             54
Name: State, dtype: int64

In [8]:
df.isnull().sum()

State                                   0
Year                                    0
Nitrogen (%)                          288
Nitrogen (Pounds/Acre)                288
Phosphorous (%)                       288
Phosphorous (Pounds/Acre)             288
Potash (%)                            294
Potash (Pounds/Acre)                  298
Area Planted (acres)                  126
Harvested Area (acres)                126
Lint Yield (Pounds/Harvested Acre)    126
dtype: int64

In [10]:
df.shape

(756, 11)

In [11]:
# Calculate the percentage of missing values for each column
missing_percentage = df.isnull().mean() * 100

# Print the percentage of missing values
print(missing_percentage)

State                                  0.000000
Year                                   0.000000
Nitrogen (%)                          38.095238
Nitrogen (Pounds/Acre)                38.095238
Phosphorous (%)                       38.095238
Phosphorous (Pounds/Acre)             38.095238
Potash (%)                            38.888889
Potash (Pounds/Acre)                  39.417989
Area Planted (acres)                  16.666667
Harvested Area (acres)                16.666667
Lint Yield (Pounds/Harvested Acre)    16.666667
dtype: float64

In [12]:
column_means = df.mean()

# Fill missing values with the mean of their respective column
df_filled = df.fillna(column_means)

C:\Users\tejes\AppData\Local\Temp\ipykernel_12648\343993380.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  column_means = df.mean()

In [13]:
df_filled.isnull().sum()

State                                 0
Year                                  0
Nitrogen (%)                          0
Nitrogen (Pounds/Acre)                0
Phosphorous (%)                       0
Phosphorous (Pounds/Acre)             0
Potash (%)                            0
Potash (Pounds/Acre)                  0
Area Planted (acres)                  0
Harvested Area (acres)                0
Lint Yield (Pounds/Harvested Acre)    0
dtype: int64

In [14]:
# Convert categorical variable into dummy/indicator variables
df_encoded = pd.get_dummies(df_filled, prefix='Category')

print(df_encoded)

     Year  Nitrogen (%)  Nitrogen (Pounds/Acre)  Phosphorous (%)  \
0    1964     99.000000               72.000000       100.000000
1    1965    100.000000               81.000000       100.000000
2    1966    100.000000               83.000000       100.000000
3    1967    100.000000               78.000000       100.000000
4    1968    100.000000               71.000000        99.000000
..    ...           ...                     ...              ...
751  2013     89.521368               87.205128        65.450855
752  2014     89.521368               87.205128        65.450855
753  2015     66.000000               65.000000        46.000000
754  2016     89.521368               87.205128        65.450855
755  2017     68.000000               77.000000        52.000000

     Phosphorous (Pounds/Acre)  Potash (%)  Potash (Pounds/Acre)  \
0                    62.000000   99.000000              63.00000
1                    63.000000  100.000000              66.00000
2                    69.000000  100.000000              70.00000
3                    71.000000  100.000000              73.00000
4                    71.000000   99.000000              73.00000
..                         ...         ...                   ...
751                  53.367521   58.660173              58.19214
752                  53.367521   58.660173              58.19214
753                  34.000000   16.000000              14.00000
754                  53.367521   58.660173              58.19214
755                  37.000000   25.000000              20.00000

     Area Planted (acres)  Harvested Area (acres)  \
0              874.279365              778.571429
1              874.279365              778.571429
2              874.279365              778.571429
3              874.279365              778.571429
4              874.279365              778.571429
..                    ...                     ...
751           4800.000000             4500.000000
752           5650.000000             5200.000000
753           7000.000000             5500.000000
754           7750.000000             4350.000000
755           7050.000000             6000.000000

     Lint Yield (Pounds/Harvested Acre)  ...  Category_Georgia  \
0                            772.487302  ...                 0
1                            772.487302  ...                 0
2                            772.487302  ...                 0
3                            772.487302  ...                 0
4                            772.487302  ...                 0
..                                  ...  ...               ...
751                          610.000000  ...                 0
752                          748.000000  ...                 0
753                          809.000000  ...                 0
754                          756.000000  ...                 0
755                          568.000000  ...                 0

     Category_Louisiana  Category_Mississippi  Category_Missouri  \
0                     0                     0                  0
1                     0                     0                  0
2                     0                     0                  0
3                     0                     0                  0
4                     0                     0                  0
..                  ...                   ...                ...
751                   0                     0                  0
752                   0                     0                  0
753                   0                     0                  0
754                   0                     0                  0
755                   0                     0                  0

     Category_New Mexico  Category_North Carolina  Category_Oklahoma  \
0                      0                        0                  0
1                      0                        0                  0
2                      0                        0                  0
3                      0                        0                  0
4                      0                        0                  0
..                   ...                      ...                ...
751                    0                        0                  0
752                    0                        0                  0
753                    0                        0                  0
754                    0                        0                  0
755                    0                        0                  0

     Category_South Carolina  Category_Tennessee  Category_Texas
0                          0                   0               0
1                          0                   0               0
2                          0                   0               0
3                          0                   0               0
4                          0                   0               0
..                       ...                 ...             ...
751                        0                   0               1
752                        0                   0               1
753                        0                   0               1
754                        0                   0               1
755                        0                   0               1

[756 rows x 24 columns]

In [15]:
df_encoded.head()

,Year,Nitrogen (%),Nitrogen (Pounds/Acre),Phosphorous (%),Phosphorous (Pounds/Acre),Potash (%),Potash (Pounds/Acre),Area Planted (acres),Harvested Area (acres),Lint Yield (Pounds/Harvested Acre),...,Category_Georgia,Category_Louisiana,Category_Mississippi,Category_Missouri,Category_New Mexico,Category_North Carolina,Category_Oklahoma,Category_South Carolina,Category_Tennessee,Category_Texas
0,1964,99.0,72.0,100.0,62.0,99.0,63.0,874.279365,778.571429,772.487302,...,0,0,0,0,0,0,0,0,0,0
1,1965,100.0,81.0,100.0,63.0,100.0,66.0,874.279365,778.571429,772.487302,...,0,0,0,0,0,0,0,0,0,0
2,1966,100.0,83.0,100.0,69.0,100.0,70.0,874.279365,778.571429,772.487302,...,0,0,0,0,0,0,0,0,0,0
3,1967,100.0,78.0,100.0,71.0,100.0,73.0,874.279365,778.571429,772.487302,...,0,0,0,0,0,0,0,0,0,0
4,1968,100.0,71.0,99.0,71.0,99.0,73.0,874.279365,778.571429,772.487302,...,0,0,0,0,0,0,0,0,0,0

In [16]:
df_encoded.isnull().sum()

Year                                  0
Nitrogen (%)                          0
Nitrogen (Pounds/Acre)                0
Phosphorous (%)                       0
Phosphorous (Pounds/Acre)             0
Potash (%)                            0
Potash (Pounds/Acre)                  0
Area Planted (acres)                  0
Harvested Area (acres)                0
Lint Yield (Pounds/Harvested Acre)    0
Category_Alabama                      0
Category_Arizona                      0
Category_Arkansas                     0
Category_California                   0
Category_Georgia                      0
Category_Louisiana                    0
Category_Mississippi                  0
Category_Missouri                     0
Category_New Mexico                   0
Category_North Carolina               0
Category_Oklahoma                     0
Category_South Carolina               0
Category_Tennessee                    0
Category_Texas                        0
dtype: int64

In [19]:
y = df_encoded['Area Planted (acres)']
X = df_encoded.drop('Area Planted (acres)', axis = 1)

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
from sklearn.neighbors import KNeighborsRegressor
knn_regressor = KNeighborsRegressor(n_neighbors=5)
knn_regressor.fit(X_train_scaled, y_train)

KNeighborsRegressor()

In [29]:
from sklearn.metrics import mean_squared_error
y_pred = knn_regressor.predict(X_test_scaled)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 59825.5759434707

In [31]:
from sklearn.metrics import r2_score
r_squared = r2_score(y_test, y_pred)
print(f"R-squared: {r_squared}")

R-squared: 0.9598209871417859